### ISSUE TITLE
Bold text is parsed as heading

### ISSUE THREAD

**Issue by smee** [rksm/clj-org-analyzer#10]
When the text in a section starts with * it seems to be interpreted as the start of a heading, even if it is markup for [bold text](https://orgmode.org/manual/Emphasis-and-monospace.html)
``` org
* Heading
:LOGBOOK:
CLOCK: [2019-08-03 Sat 09:00]--[2019-08-03 Sat 10:11] =>  1:11
:END:
** Subheading with bold text
:LOGBOOK:
CLOCK: [2019-08-04 Sun 09:00]--[2019-08-04 Sun 10:11] =>  1:11
:END:
*This bold text* should not be interpreted as a heading
** another subheading
:LOGBOOK:
CLOCK: [2019-08-05 Mon 09:00]--[2019-08-05 Mon 10:11] =>  1:11
:END:
```
The visualization shows the bold text as part of a heading:
![image](https://user-images.githubusercontent.com/36397/63352377-4c3fbb80-c361-11e9-9992-b39848be9fe2.png)

**Comment by rksm** [comment]
Fixed in [0.3.4](https://github.com/rksm/clj-org-analyzer/releases/tag/0.3.4)
