### ISSUE TITLE
org-mode timestamps allow 24:00

### ISSUE THREAD

**Issue by bhipple** [rksm/clj-org-analyzer#11]
To reproduce, in org-mode try inserting a timestamp at "10pm+2", and observe that we get this:

```
<2019-09-14 Sat 22:00-24:00>
```

This will be correctly displayed on the org-agenda page.  Interestingly, times beyond 24:00 are not allowed and will prevent the agenda from rendering.

When clj-org-analyzer tries to parse this, it returns:

```
$ java -jar ./org-analyzer-1.0.0.jar ~/org
java.time.DateTimeException: Invalid value for HourOfDay (valid values 0 - 23): 24
              ValueRange.java:311 java.time.temporal.ValueRange.checkValidValue
             ChronoField.java:703 java.time.temporal.ChronoField.checkValidValue
               LocalTime.java:339 java.time.LocalTime.of
           LocalDateTime.java:362 java.time.LocalDateTime.of
...
```

Do you think it makes sense to update org-analyzer to support this?  In the meantime an easy workaround for users is to just run `sed -i 's/24:00/23:59/g' **/*.org`

**Comment by rksm** [comment]
Oh boy.

**Comment by rksm** [comment]
Thanks for reporting! 24h strings will be automatically replaced with 23:59 for now.
