### ISSUE TITLE
org-analyzer-start: Wrong type argument: sequencep, file-error

### ISSUE THREAD

**Issue by gamrot** [rksm/clj-org-analyzer#12]
Hey,
I've installed org-analyzer from MELPA, but when I run `org-analyzer-start` I get `org-analyzer-start: Wrong type argument: sequencep, file-error`.

Why is this the case?

**Comment by rksm** [comment]
Hmm. 

1. When you M-x `toggle-debug-on-error`, what does the stack trace look?
2. Does a browser window open when you eval (`M-:`) `(async-shell-command (format "java -jar %s" (org-analyzer-locate-jar)))`?
3. What is the eval result of `(org-analyzer-effective-org-dir)`?

Thanks!

**Comment by gamrot** [comment]
1. Stack trace

`Debugger entered--Lisp error: (wrong-type-argument sequencep file-error)
  org-analyzer-start-process("~/org")
  org-analyzer-start()
  funcall-interactively(org-analyzer-start)
  call-interactively(org-analyzer-start record nil)
  command-execute(org-analyzer-start record)
  execute-extended-command(nil "org-analyzer-start" #("org anal\norg-analyzer-start\norg-analyzer-stop" 8 9 (read-only nil) 9 12 (face ((:foreground "#d1f1a9") ivy-current-match ivy-minibuffer-match-face-3) mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 12 13 (face ((:foreground "#d1f1a9") ivy-current-match ivy-minibuffer-match-face-1) mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 13 16 (face ((:foreground "#d1f1a9") ivy-current-match ivy-minibuffer-match-face-4) mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 16 27 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) face ((:foreground "#d1f1a9") ivy-current-match) read-only nil) 27 28 (read-only nil) 28 31 (face (ivy-minibuffer-match-face-3 ivy-minibuffer-match-face-1) mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 31 32 (face ivy-minibuffer-match-face-1 mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 32 35 (face (ivy-minibuffer-match-face-4 ivy-minibuffer-match-face-1) mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 35 45 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil)))
  funcall-interactively(execute-extended-command nil "org-analyzer-start" #("org anal\norg-analyzer-start\norg-analyzer-stop" 8 9 (read-only nil) 9 12 (face ((:foreground "#d1f1a9") ivy-current-match ivy-minibuffer-match-face-3) mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 12 13 (face ((:foreground "#d1f1a9") ivy-current-match ivy-minibuffer-match-face-1) mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 13 16 (face ((:foreground "#d1f1a9") ivy-current-match ivy-minibuffer-match-face-4) mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 16 27 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) face ((:foreground "#d1f1a9") ivy-current-match) read-only nil) 27 28 (read-only nil) 28 31 (face (ivy-minibuffer-match-face-3 ivy-minibuffer-match-face-1) mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 31 32 (face ivy-minibuffer-match-face-1 mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 32 35 (face (ivy-minibuffer-match-face-4 ivy-minibuffer-match-face-1) mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil) 35 45 (mouse-face ivy-minibuffer-match-highlight help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) read-only nil)))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)`

2. Nope. I only get `'java' is not recognized as an internal or external command,
operable program or batch file.`
3. `~/org`

**Comment by rksm** [comment]
I assume you have java installed?

Is it in your exec-path? https://stackoverflow.com/questions/8606954/path-and-exec-path-set-but-emacs-does-not-find-executable

What does `(executable-find "java")` say?

**Comment by gamrot** [comment]
It says `"c:/ProgramData/Oracle/Java/javapath/java.exe"`

**Comment by rksm** [comment]
Alright, I'm pretty sure that the issue is that your `org-directory` which points to "~/org" does not exist. On Windows this expands to something weird like `c:/Users/username/AppData/Roaming/org` which you likely don't want to use.

I created a new version of org-analyzer that accounts for that and that allows you to choose your org files / directories from within the app. The update should be on MELPA within 24h.

You might still want to set your `org-directory` to the location where you keep your org files, I thing emacs org pretty much expects that.

In case I'm wrong please let me know if the issue still exist.

Thanks!

**Comment by gamrot** [comment]
Great! It works, more or less :) 

I've set the `org-directory` to `~/Desktop/org` where I keep my org files. Unfortunately, org-analyzer does not find my org files and I need to manually add them. Do you know why this might be the case? I've set up `org-directory` like this:

`(setq org-directory "~/Desktop/org")
(setq org-analyzer-start-process "~/Desktop/org")`

**Comment by rksm** [comment]
on Windows `~/Desktop/org` expands to `c:/Users/$USERNAME/AppData/Desktop/org` but this is not your Desktop folder. Do `(setq org-directory "c:/Users/$USERNAME/Desktop/org")` (with $USERNAME your windows user) and then M-x `org-analyzer-start`.

**Comment by rksm** [comment]
(to see how path get resolved you can evaluate expressions like `(expand-file-name "~/Deskop/org")` in emacs)
