### ISSUE TITLE
wrong jar file in emacs release 0.3.0

### ISSUE THREAD

**Issue by unhammer** [rksm/clj-org-analyzer#2]
```
* current projects
** org clockin visualization
*** ui - improvements (tags, filter, day viz)
    :LOGBOOK:
    CLOCK: [2019-08-04 Sun 23:35]--[2019-08-04 Sun 23:49] =>  0:14
    CLOCK: [2019-08-04 Sun 13:51]--[2019-08-04 Sun 15:06] =>  1:15
    CLOCK: [2019-08-04 Sun 04:25]--[2019-08-04 Sun 05:16] =>  0:51
    :END:
```
should be equivalent to the example in the readme 
```
* current projects
** org clockin visualization
*** ui - improvements (tags, filter, day viz)
:LOGBOOK:
CLOCK: [2019-08-04 Sun 23:35]--[2019-08-04 Sun 23:49] =>  0:14
CLOCK: [2019-08-04 Sun 13:51]--[2019-08-04 Sun 15:06] =>  1:15
CLOCK: [2019-08-04 Sun 04:25]--[2019-08-04 Sun 05:16] =>  0:51
:END:
```

but I see nothing when it's indented

**Comment by unhammer** [comment]
Oh, it seems to handle them with https://github.com/rksm/clj-org-analyzer/releases/download/0.3.0/org-analyzer-0.3.0.jar – just not with the jar in https://github.com/rksm/clj-org-analyzer/releases/download/0.3.0/org-analyzer-for-emacs-0.3.0.tar.gz

**Comment by rksm** [comment]
Oops, sorry, will be fixed!

**Comment by rksm** [comment]
https://github.com/rksm/clj-org-analyzer/releases/download/0.3.2/org-analyzer-for-emacs-0.3.2.tar.gz should have the recent jar
