### ISSUE TITLE
Archive org files ignored

### ISSUE THREAD

**Issue by smee** [rksm/clj-org-analyzer#7]
In my workflow I tend to move finished TODOs into an `.org_archive` file. These files are not read and analyzed, correct? I can't see them in the list of org files and their entries do not show up. Could/should they be analyzed automatically? If not, maybe would you consider adding a flag to in-/exclude those archive files?

**Comment by rksm** [comment]
Absolutely, will do that. Is `.org_archive` the commonly used extension for archive files?

**Comment by rksm** [comment]
0.3.2 will include archives by default. I'll add a command line switch for disabling that feature later.
