### ISSUE TITLE
Org-links in the heading

### ISSUE THREAD

**Issue by agzam** [rksm/clj-org-analyzer#8]
It would be nice if there's a link in the heading it displays it in a nicer format

![image](https://user-images.githubusercontent.com/1091022/63216891-6d9a7080-c0f1-11e9-817d-3e7045075468.png)

**Comment by rksm** [comment]
Coming!

**Comment by rksm** [comment]
Thanks for the precise report, it's fixed now in [0.3.4](https://github.com/rksm/clj-org-analyzer/releases/tag/0.3.4)

**Comment by agzam** [comment]
That was quick. Thank you @rksm !
