### ISSUE TITLE
Wrongly associated parent

### ISSUE THREAD

**Issue by smee** [rksm/clj-org-analyzer#9]
I tried to parse an org file that had nested headings that were nonconsecutive: Under the two-star heading I had four stars:
``` org
* AAAAA
** one below AAAAA
:LOGBOOK:
CLOCK: [2018-11-03 Sat 09:00]--[2018-11-03 Sat 10:11] =>  1:11
:END:
**** four below AAAAA
this should not show the elements from BBBB as children
* BBBBB
** should be under BBB
:LOGBOOK:
CLOCK: [2018-11-01 Thu 09:45]--[2018-11-01 Thu 17:33] =>  7:48
CLOCK: [2018-11-02 Fri 08:11]--[2018-11-02 Fri 15:15] =>  7:04
:END:
```
The visualization then seems to wrongly associate the children of the BBBBB (a sibling of AAAAA) as descendents of AAAAA:
![image](https://user-images.githubusercontent.com/36397/63350694-311f7c80-c35e-11e9-857f-e81cc1c59554.png)

**Comment by rksm** [comment]
Thanks for the precise report, it's fixed now in [0.3.4](https://github.com/rksm/clj-org-analyzer/releases/tag/0.3.4)
